# fly.toml app configuration file generated for lingering-night-727 on 2023-06-26T17:46:29+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "lingering-night-727"
primary_region = "ams"

[env]
  PORT = "8080" # add this

[[services]]
  internal_port = 8080
  protocol = "tcp"
  processes = ["app"]
  http_checks = []

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[build]
  [build.args]
    NODE_VERSION = "16.20.1"
